id = "everforest"
name = "Everforest"

[bat]
theme = "Everforest Dark"

[starship]
config = "everforest.toml"

[lazygit]
config = "everforest.yml"

[alacritty]
theme = "everforest.toml"

[nvim]
colorscheme = "everforest"

[tmux]
theme = "everforest.conf"

[palette]
background = "#2d353b"
foreground = "#d3c6aa"
selection = "#859289"
black = "#343f44"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
bright_black = "#859289"
bright_red = "#e67e80"
bright_green = "#a7c080"
bright_yellow = "#dbbc7f"
bright_blue = "#7fbbb3"
bright_magenta = "#d699b6"
bright_cyan = "#83c092"
bright_white = "#d3c6aa"
